export const ADD_ERROR  = "ADD_ERROR";
export const REMOVE_ERROR  = "REMOVE_ERROR";
export const SET_CURRENT_USER  = "SET_CURRENT_USER";
export const SET_PROMO  = "SET_PROMO";
export const LOAD_EVENTS = "LOAD_EVENTS";
export const REMOVE_EVENT = "REMOVE_EVENT";
export const LOAD_DISCUSSIONS = "LOAD_DISCUSSIONS";
export const REMOVE_DISCUSSION = "REMOVE_DISCUSSION";
